### ISSUE TITLE
Django 1.11 hashed_name() Error

### ISSUE THREAD

**Issue by soasuk** [adamcharnock/django-pipeline-forgiving#1]
After an upgrade from Django 1.10 to 1.11 (on Python 2.7) I got an error when accessing any page, including the admin.

Exception Type: TypeError at / Exception Value: hashed_name() got an unexpected keyword argument 'filename'

The problem stopped when the original 'pipeline.storage.PipelineStorage' was used. I'm not looking for a fix as this plugin hasn't been updated in some time however it may save some time if anyone else  comes across it.

Traceback:
```
File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/response.py" in rendered_content
  84.         content = template.render(context, self._request)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render
  207.                     return self._render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/pipeline/templatetags/pipeline.py" in render
  140.         return self.render_compressed(package, package_name, 'css')

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/pipeline/templatetags/pipeline.py" in render_compressed
  69.                                                  package_type)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/pipeline/templatetags/pipeline.py" in render_compressed_output
  82.         return method(package, package.output_filename)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/pipeline/templatetags/pipeline.py" in render_css
  147.             'url': mark_safe(staticfiles_storage.url(path))

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py" in url
  162.         return self._url(self.stored_name, name, force)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py" in _url
  141.                 hashed_name = hashed_name_func(*args)

File "/home/itsol/virtualenvs/vote/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py" in stored_name
  365.                 self.hashed_name(name, content=None, filename=intermediate_name)

Exception Type: TypeError at / Exception Value: hashed_name() got an unexpected keyword argument 'filename'
```
